name: chat_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  flutter_bloc:
  shared_preferences: ^2.0.15
  sidebarx: ^0.14.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  grouped_list: ^5.1.2
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.1
  path: ^1.8.2
  path_provider: ^2.0.11
  sqflite_common: ^2.4.0+2
  sqflite_common_ffi: ^2.2.0+1
  grpc: ^3.1.0
  equatable: ^2.0.5
  protobuf: ^2.1.0
  connectivity_plus: ^3.0.2
  freezed: ^2.2.0
  custom_pop_up_menu: ^1.2.4
  blur: ^3.1.0
  get_it: ^7.2.0
  stream_transform: ^2.1.0
  internet_connection_checker: ^1.0.0+1
  async: ^2.9.0
  dio: ^4.0.6
  alfred: ^1.0.0+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
   assets:
     - assets/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

   uses-material-design: true
