name: server
description: A sample command-line server.
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  grpc: ^3.1.0
  sqflite_common: ^2.4.0+2
  sqflite_common_ffi: ^2.2.0+1
  path_provider: ^2.0.11
  path: ^1.8.2
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  dio: ^4.0.6


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
