name: server
description: A sample command-line server.
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  grpc: ^3.1.0
  sqflite_common: ^2.4.0+2
  sqflite_common_ffi: ^2.2.0+1
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
